### ISSUE TITLE
error when runing the app.py

### ISSUE THREAD

**Issue by JoshonSmith** [naver-ai/DenseDiffusion#4]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:42<00:00,  1.17it/s]
Traceback (most recent call last):
  File "/data/miniconda3/envs/dragdiff/lib/python3.8/site-packages/gradio/routes.py", line 439, in run_predict
    output = await app.get_blocks().process_api(
  File "/data/miniconda3/envs/dragdiff/lib/python3.8/site-packages/gradio/blocks.py", line 1384, in process_api
    result = await self.call_function(
  File "/data/miniconda3/envs/dragdiff/lib/python3.8/site-packages/gradio/blocks.py", line 1089, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/data/miniconda3/envs/dragdiff/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/data/miniconda3/envs/dragdiff/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/data/miniconda3/envs/dragdiff/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/data/miniconda3/envs/dragdiff/lib/python3.8/site-packages/gradio/utils.py", line 700, in wrapper
    response = f(*args, **kwargs)
  File "gradio_app.py", line 218, in process_generation
    image = pipe(prompts[:1]*bsz, latents=latents).images
  File "/data/miniconda3/envs/dragdiff/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/miniconda3/envs/dragdiff/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 713, in __call__
    do_denormalize = [not has_nsfw for has_nsfw in has_nsfw_concept]
TypeError: 'bool' object is not iterable

**Comment by YunjiKim** [comment]
not sure but could you try with diffusers v0.12.1?
